Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Style/DefWithParentheses:
  Description: 'Use def with parentheses when there are arguments.'
  Enabled: true
